/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.unime.math.functioneasy.gui;

import static br.com.unime.math.functioneasy.util.PropertiesBR.GRAPH_NAME;
import static br.com.unime.math.functioneasy.util.PropertiesBR.LABEL_APP_NAME;
import static br.com.unime.math.functioneasy.util.PropertiesBR.LABEL_APP_VERSION;
import static br.com.unime.math.functioneasy.util.PropertiesBR.LABEL_TITLE_ERROR;
import static br.com.unime.math.functioneasy.util.PropertiesBR.MESSAGE_ERROR_1;
import static br.com.unime.math.functioneasy.util.PropertiesBR.MESSAGE_ERROR_2;
import static br.com.unime.math.functioneasy.util.PropertiesBR.MESSAGE_ERROR_3;
import static br.com.unime.math.functioneasy.util.PropertiesBR.MESSAGE_ERROR_4;
import static br.com.unime.math.functioneasy.util.PropertiesBR.MESSAGE_ERROR_5;
import static br.com.unime.math.functioneasy.util.PropertiesBR.MESSAGE_ERROR_6;
import static br.com.unime.math.functioneasy.util.PropertiesBR.MESSAGE_ERROR_7;
import static br.com.unime.math.functioneasy.util.PropertiesBR.MESSAGE_ERROR_8;
import static br.com.unime.math.functioneasy.util.PropertiesBR.SEPARATOR;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import br.com.unime.math.functioneasy.model.Coordinate;
import br.com.unime.math.functioneasy.util.CoordinateGenerator;
import br.com.unime.math.functioneasy.util.GraphGenerator;
import br.com.unime.math.functioneasy.util.NumberUtils;
import expr.SyntaxException;

/**
 *
 * @author Mauricio Barbosa
 */
public class FunctionEasyUI extends JFrame {
    
    private static String APP_PATH;
    private static final String IMAGES_FOLDER = "graphs";
    
    private GraphGenerator graphGenerator;
    private CoordinateGenerator coordinateGenerator;
    /**
     * Creates new form FunctionEasyUI
     */
    public FunctionEasyUI() {
    	coordinateGenerator = new CoordinateGenerator();
        try {
            APP_PATH = new File(".").getCanonicalPath();
        } catch (IOException ex) {
            Logger.getLogger(FunctionEasyUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        graphImage = new javax.swing.JLabel();
        inputEquation = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputXMin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputXMax = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        graphImage.setIcon(new javax.swing.ImageIcon(APP_PATH + File.separator + "graph.png")); // NOI18N

        jLabel1.setText("F(X) =");

        jLabel2.setText("X(min) =");

        jLabel3.setText("X(max) =");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateGraph(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputXMin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputXMax, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputEquation, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(486, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputEquation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputXMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputXMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graphImage, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setIconImage(new ImageIcon(APP_PATH + File.separator + "icon.png").getImage());
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateGraph(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	String equation = inputEquation.getText().trim().toLowerCase();
    	String xMin = inputXMin.getText().trim().toLowerCase();
    	String xMax = inputXMax.getText().trim().toLowerCase();
    	
    	if (validateInput(equation, xMin, xMax)) {
    		Map<Integer, List<Coordinate>> coordinates;
			try {
				coordinates = coordinateGenerator.generate(equation, xMin, xMax);
				graphGenerator = new GraphGenerator(GRAPH_NAME, coordinates);
				ImageIcon newGraph = graphGenerator.generateGraphOnImage(getImagePath(), graphImage.getWidth(), graphImage.getHeight());
				graphImage.setIcon(newGraph);
				pack();
			} catch (SyntaxException e1) {
				JOptionPane.showMessageDialog(this, MESSAGE_ERROR_8, LABEL_TITLE_ERROR, JOptionPane.ERROR_MESSAGE);
			} catch (IOException e) {
				java.util.logging.Logger.getLogger(FunctionEasyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
			}
    	}
    	
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean validateInput(String equation, String xMin, String xMax) {

    	if (equation.isEmpty()) {
    		JOptionPane.showMessageDialog(this, MESSAGE_ERROR_1, LABEL_TITLE_ERROR, JOptionPane.ERROR_MESSAGE);
    		return false;
    	}

    	if (xMin.isEmpty()) {
    		JOptionPane.showMessageDialog(this, MESSAGE_ERROR_2, LABEL_TITLE_ERROR, JOptionPane.ERROR_MESSAGE);
    		return false;
    	}

    	if (xMax.isEmpty()) {
    		JOptionPane.showMessageDialog(this, MESSAGE_ERROR_3, LABEL_TITLE_ERROR, JOptionPane.ERROR_MESSAGE);
    		return false;
    	}
    	
    	String[] listEquation = equation.split(SEPARATOR);
    	String[] listXMin = xMin.split(SEPARATOR);
    	String[] listXMax = xMax.split(SEPARATOR);
    	
    	if (listEquation.length != listXMin.length) {
    		JOptionPane.showMessageDialog(this, MESSAGE_ERROR_4, LABEL_TITLE_ERROR, JOptionPane.ERROR_MESSAGE);
    		return false;
    	}
    	
    	if (listEquation.length != listXMax.length) {
    		JOptionPane.showMessageDialog(this, MESSAGE_ERROR_5, LABEL_TITLE_ERROR, JOptionPane.ERROR_MESSAGE);
    		return false;
    	}
    	
    	for (String valueXMin : listXMin) {
			if (!NumberUtils.isNumber(valueXMin)) {
				JOptionPane.showMessageDialog(this, MESSAGE_ERROR_6, LABEL_TITLE_ERROR, JOptionPane.ERROR_MESSAGE);
	    		return false;
			}
		}
    	
    	for (String valueXMax : listXMax) {
			if (!NumberUtils.isNumber(valueXMax)) {
				JOptionPane.showMessageDialog(this, MESSAGE_ERROR_7, LABEL_TITLE_ERROR, JOptionPane.ERROR_MESSAGE);
	    		return false;
			}
		}
    	
		return true;
	}

	private String getImagePath() {
        return APP_PATH + File.separator + IMAGES_FOLDER + File.separator + "graph_" + System.currentTimeMillis() + ".png";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunctionEasyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunctionEasyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunctionEasyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunctionEasyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new FunctionEasyUI();
                frame.setTitle(LABEL_APP_NAME + " " + LABEL_APP_VERSION);
                frame.setResizable(false);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel graphImage;
    private javax.swing.JTextField inputEquation;
    private javax.swing.JTextField inputXMax;
    private javax.swing.JTextField inputXMin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
